version: '3.8'

services:
  # Service FastAPI (désactivé pour l'instant)
  # fastapi:
  #   build: .
  #   container_name: fastapi_bdia
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     - DATABASE_URL=postgresql://bdia_user:bdia_pass@postgres/bdia_db
  #     - MONGODB_URI=mongodb://mongo:27017/logs_db
  #   depends_on:
  #     - postgres
  #     - mongo
  #   networks:
  #     - app-network

  postgres:
    image: postgres:13
    container_name: postgres_bdia
    environment:
      POSTGRES_USER: bdia_user
      POSTGRES_PASSWORD: bdia_pass
      POSTGRES_DB: bdia_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_bdia
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@bdia.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - app-network

  # ✅ MongoDB pour les logs
  mongo:
    image: mongo:latest
    container_name: mongo_logs
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: logs_db
    volumes:
      - mongodata:/data/db
    networks:
      - app-network

  # (Optionnel) Interface web pour MongoDB
  mongo-express:
    image: mongo-express
    container_name: mongo_express_logs
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    depends_on:
      - mongo
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
  mongodata:
